title: Pilar Kukuh Bintang Rachmadi
logo: /assets/IMG_6068.JPG
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
